title: Indivisible Cobb
email: email@indivisiblecobb.com
description: Official website for Indivisible Cobb. Follow us for information on Cobb County GA activism and for resources on being equipped and prepared to fight tyranny in our country and county.
baseurl: "/indivisibleCobb"
url: "https://indivisibleCobb.com"

